### ISSUE TITLE
Prefer configuring SDK version via environment variables over buildpack.yml

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/dotnet-core-sdk#152]
## Summary
The current implementation allows a buildpack user to choose a .Net Core SDK version using a `buildpack.yml` configuration file with the following contents:

```yaml
dotnet-sdk:
  version: 2.1.804
```

After the approval of [RFC0002](https://github.com/paketo-buildpacks/dotnet-core/blob/main/rfcs/0002-buildpack-yml-to-env-var.md) we should be preferring to allow that configuration via an environment variable like:

```shell
BP_DOTNET_SDK_VERSION="2.1.804"
```

### Deprecation Notice
The buildpack should emit a deprecation notice via log output when a `buildpack.yml` file appears in the application source code with configuration for this buildpack. The deprecation notice should appear similar to notices that have been implemented in [other](https://github.com/paketo-buildpacks/mri/blob/4e486427aa4ca316016403686ca1755cab9f554c/build.go#L68-L73) [buildpacks](https://github.com/paketo-buildpacks/go-dist/blob/de73c417686ab36e7686d881e2d0c769939f8ea5/build.go#L53-L58).

**Comment by sophiewigmore** [comment]
After our initial investigation into this issue, we believe that we should not implement support for setting the SDK version either through the new `BP_DOTNET_SDK_VERSION` variable, or through the `buildpack.yml`.

The reason for this is because the the .NET Core Runtime buildpack always sets a `RUNTIME_VERSION` that the SDK buildpack picks up and uses to find a compatible SDK version. Even in the case where a user would want to specify their own SDK version through `BP_DOTNET_SDK_VERSION`/`buildpack.yml`, it would never have an effect with our current buildpacks since `RUNTIME_VERSION` trumps everything else. 
Users could end up in a situation where they request an SDK but the `RUNTIME_VERSION` from .NET Core Runtime picks something else:
```
[builder] Paketo .NET Core SDK Buildpack 0.1.7
[builder]   Resolving .NET Core SDK version
[builder]     Candidate version sources (in priority order):
[builder]       RUNTIME_VERSION -> "5.0.201"
[builder]       buildpack.yml   -> "2.1.813"
[builder]       <unknown>       -> "*"
```

It's more confusing for a user to to expect to be able to set the SDK version, and then not be able to. It probably makes more sense to just disable this configuration all together.

While we understand the need for modular buildpacks that can function alone, or in conjunction with other buildpacks besides just Paketo ones, the .NET Core Runtime, ASPNet, and SDK buildpacks are just extremely hard to separate by nature. We're trying to draw the line between having "modular" buildpacks and having functionality that makes sense to users.

**Comment by fg-j** [comment]
Suppose that `BP_DOTNET_SDK_VERSION` gets higher priority than `RUNTIME_VERSION`, such that setting the environment variable *could* have an effect.

Would a user be able to meaningfully select from a set of versions available in the buildpack? Does the buildpack distribute more than one SDK version that can produce a working image in conjunction with a given runtime version?

For example, if your runtime version is `3.*` based on something in your csproj, would selecting a dotnet SDK with version `5.*` produce a functional build? What about selecting a different patch version of the SDK than the one that the buildpack would select for you?

I understand that right now, the buildpack maintains a [one-to-one mapping](https://github.com/paketo-buildpacks/dotnet-core-sdk/blob/main/buildpack.toml#L69-L91) between runtime versions and SDK versions. But that doesn't necessarily mean that the mapping is the only possible one that'll produce a functional build. I'd like to see some investigation into that question.

**Comment by sophiewigmore** [comment]
We tried out putting the `buildpack.yml` version source as the highest priority, and then built a few apps with mis-matched SDK and Runtime versions. For example, we built a 3.1 App that wanted SDK version 3.1.407, but we requested 2.1.813 in the buildpack.yml. The issue with the mismatched versions arises in the Dotnet Publish buildpack, because an app cannot be published with non-compatible Framework and SDK versions. See the log output below, the publish buildpack fails with ` It was not possible to find any compatible framework version`:

```
[builder] Paketo .NET Core Runtime Buildpack 0.1.9
[builder]   Resolving Dotnet Core Runtime version
[builder]     Candidate version sources (in priority order):
[builder]       simple_3_0_app.csproj -> "3.1.0"
[builder]       <unknown>             -> ""
[builder]
[builder]     No exact version match found; attempting version roll-forward
[builder]
[builder]     Selected dotnet-runtime version (using simple_3_0_app.csproj): 3.1.13
[builder]
[builder]   Reusing cached layer /layers/paketo-buildpacks_dotnet-core-runtime/dotnet-core-runtime
[builder] ...
[builder]
[builder] Paketo .NET Core SDK Buildpack 4.4.4
[builder]   Resolving .NET Core SDK version
[builder]     Candidate version sources (in priority order):
[builder]       buildpack.yml         -> "2.1.813"
[builder]       RUNTIME_VERSION       -> "3.1.407"
[builder]       simple_3_0_app.csproj -> "3.1.*"
[builder]       <unknown>             -> "*"
[builder]
[builder]     Selected .NET Core SDK version (using buildpack.yml): 2.1.813
[builder]
[builder]   Executing build process
[builder]     Installing .NET Core SDK 2.1.813
[builder]       Completed in 11.611s
[builder] ...
[builder]
[builder] Paketo .NET Publish Buildpack 0.1.5
[builder]   Executing build process
[builder]     Running 'dotnet publish /workspace --configuration Release --runtime ubuntu.18.04-x64 --self-contained false --output /tmp/dotnet-publish-output227051376'
[builder]       Failed after 3.219597ms
[builder]         It was not possible to find any compatible framework version
[builder]         The framework 'Microsoft.NETCore.App', version '2.1.25' was not found.
[builder]           - The following frameworks were found:
[builder]               3.1.13 at [/workspace/.dotnet_root/shared/Microsoft.NETCore.App]
```

This isn't an issue unless the Dotnet Publish buildpack is needed. The only use case for this is when there are multiple compatible SDK versions provided by the buildpack that the user will pick (such as SDK version 3.1.406 or 3.1.407 for a 3.1 Framework version). 

We could allow for this use case, but it would be at the user's own risk. It should be clear (in the docs) that if a user wants to specify their own version, it must be a compatible version or the build will fail.

@fg-j / @ForestEckhardt should we continue with this approach (i.e. Putting the `buildpack.yml` and `BP_SDK_VERSION` as higher priority than `RUNTIME_VERSION` at the user's own risk)?

**Comment by fg-j** [comment]
Since the buildpack currently only ships 2 patch versions of each major/minor of the SDK, the "configurability" is slim right now. For the sake of simplicity, I'd be okay with leaving out the ability to specify a `BP_SDK_VERSION` individually. If we get feedback saying it's imperative to be able to select this version, we can add configurability later on. (Like how the Python buildpacks are adding the ability to configure a separate pip version after user feedback.) 
@ForestEckhardt, what's your vote?

**Comment by ForestEckhardt** [comment]
I am also fine with omitting it for the time being.

**Comment by sophiewigmore** [comment]
Closing this out  for now then!

**Comment by sophiewigmore** [comment]
https://github.com/paketo-buildpacks/dotnet-core-sdk/issues/170 is open to deprecate the `buildpack.yml` configurations.
