### ISSUE TITLE
Cannot build .NET app

### ISSUE THREAD

**Issue by johnkors** [paketo-buildpacks/dotnet-core-sdk#506]
Hi,

Tell me if I'm missing something - but I'm getting errors trying to build a .NET app using this builder.

```bash
$ pack build hello --builder paketobuildpacks/dotnet-core-sdk

latest: Pulling from paketobuildpacks/dotnet-core-sdk
Digest: sha256:3baceaeb9ebcf93286033bbf2946b852b536a34adb1fa118c4ef07e10373c6d2
Status: Image is up to date for paketobuildpacks/dotnet-core-sdk:latest
ERROR: failed to build: invalid builder paketobuildpacks/dotnet-core-sdk: builder index.docker.io/paketobuildpacks/dotnet-core-sdk:latest missing label io.buildpacks.builder.metadata -- try recreating builder
```

**Comment by sophiewigmore** [comment]
@johnkors Ah, try the buildpack prefixed with `docker.io`, so it looks like `--buildpack docker.io/paketobuildpacks/dotnet-core`

I'm surprised we need that.. I swear I've done without the docker prefix many times before but I did encounter the same issue locally just now when I tried it

**Comment by sophiewigmore** [comment]
What error do you get when you use the builder?

**Comment by johnkors** [comment]
I think I need help setting up the configuration for it to work. The build fails locating project references (dependencies). 

Ex:

```
src/
- src/app/app.csproj
- src/other/other.csproj
```

Here app.csproj contains a ref to `other.csproj` thru a `ProjectReference`. 
- Running `pack` from the `/src/app/` folder fails the build, since the build context is isolated to the `/src/app` folder.
- Running it on a sln is not currently supported if I understood you in another ticket.

Is there a way thru config to run pack, so I can run it from the `/src` folder and specify the project to build/publish explicitly?

**Comment by sophiewigmore** [comment]
In that case, you'll need to set the `BP_DOTNET_PROJECT_PATH` environment variable to `src/app` to tell the buildpack which project to look at as the root

**Comment by sophiewigmore** [comment]
Great. It's interesting that your build time increased by 5X. Do you notice any speed-up in your rebuilds? The buildpacks do have the benefit of performing some cache optimizations for your rebuilds.

I also wonder how much of that time might be related to downloading the full stack image/full builder. The full builder specifically has a lot of buildpacks, and a plethora of OS-level packages to accommodate builds for a large set of different languages. We also ship a buildpackless version of the full builder, so it has all the same OS-level packages, but no buildpacks, and then you may provide your own buildpack (since you know you definitely want .NET Core).

That'd look like
```
pack build hello \
 --builder paketobuildpacks/builder:buildpackless-full \
--buildpack paketo-buildpacks/dotnet-core
 -e BP_DOTNET_PROJECT_PATH=./src/MyWebApp  
```

**Comment by sophiewigmore** [comment]
@johnkors is this issue resolved for you now?

**Comment by johnkors** [comment]
Yes, thanks!

**Comment by sophiewigmore** [comment]
Great! I'm going to close this issue out, but happy to continue the conversation about increases in build speed if needed!
