### ISSUE TITLE
Request to Use SHA256 in manifest instead of SHA512 to support Offline Kubernetes builds

### ISSUE THREAD

**Issue by ChuckQuinnIV** [paketo-buildpacks/dotnet-core-sdk#575]
The `dependency-mapping` service binding currently cannot be used in Kubernetes environments with buildpacks using SHA512 checksums, as the format for specifying an alternative checksum defined in [RFC 10](https://github.com/paketo-buildpacks/rfcs/blob/main/text/0010-dependency-mappings.md) includes a colon, which is not usable as a Kubernetes secret key. A related issue has been opened here: https://github.com/paketo-buildpacks/packit/issues/521

To allow users to run dotnet builds in offline Kubernetes environments, would it be possible to use SHA256 in this buildpack's buildpack.toml until an alternate format has been defined?

**Comment by sophiewigmore** [comment]
Hey @ChuckQuinnIV, to be clear - if you're using a dependency mapping, can't you provide the checksum as a `SHA256`, or do you run into an error?

**Comment by ChuckQuinnIV** [comment]
Happy to run that test & respond back - my understanding was that the `dependency-mapping` service binding would only apply to the checksums published in the buildpack's `buildpack.toml`, but I'll see what happens if I plug in the unpublished SHA256 checksums.

**Comment by ChuckQuinnIV** [comment]
Confirmed that using the unpublished SHA256 checksum does not keep the buildpack offline - which makes some sense, as without the buildpack declaring the SHA256 checksum of the dependency, it wouldn't know what file it's associated to without an internet connection.

Results below show the `dotnet-core-aspnet-runtime` buildpack, but I imagine issue is similar between the two buildpacks as both use SHA512 - happy to move issue if not:

```
Paketo Buildpack for ASP.NET Core Runtime 0.3.24

  Resolving ASP.NET Core Runtime version

    Candidate version sources (in priority order):

      runtimeconfig.json -> "7.0.0"

      <unknown>          -> ""

 

    No exact version match found; attempting version roll-forward

 

    Selected ASP.NET Core Runtime version (using runtimeconfig.json): 7.0.11

 

  Executing build process

    Installing ASP.NET Core Runtime 7.0.11

failed to fetch dependency: failed to make request: Get https://download.visualstudio.microsoft.com/download/pr/dc2c0a53-85a8-4fda-a283-fa28adb5fbe2/8ccade5bc400a5bb40cd9240f003b45c/aspnetcore-runtime-7.0.11-linux-x64.tar.gz: dial tcp 93.184.215.201:443: i/o timeout

ERROR: failed to build: exit status 1
```

**Comment by sophiewigmore** [comment]
@ChuckQuinnIV thanks for verifying, it's been a minute since I've worked with the dependency mappings. I totally see what you mean -  you're cornered into using whatever algorithm is used in the `buildpack.toml`. I totally get why you're stuck now if you can't provide a binding with a `-`. 

I think in terms of this issue, I'm more inclined to make the fix on the `packit` side and allow for any algorithm to be used on K8s than to change the `buildpack.toml` here to use a different algorithm than what Microsoft provides for the dependency. I know it's likely to be a quicker change if we do it here in the buildpack, but I'd rather A. keep using the checksums as provided from upstream wherever possible and B. enable the entire Paketo ecosystem to leverage the feature

**Comment by ChuckQuinnIV** [comment]
Makes sense - eager to get offline builds working with .NET, but completely understand wanting a strategic fix here.

**Comment by sophiewigmore** [comment]
Let's continue the discussion on https://github.com/paketo-buildpacks/packit/issues/521 and see how we can move the ball forward on that issue
